<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb8d06bb73d53a2e8e2b1fa1ec0a90538
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb8d06bb73d53a2e8e2b1fa1ec0a90538::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb8d06bb73d53a2e8e2b1fa1ec0a90538::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
